---
name: Tests

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install -y pkg-config devscripts
          ./tests/ci/install_openssl.sh $HOME/.openfortivpn-deps
      - name: Build
        run: |
          ./autogen.sh
          export PKG_CONFIG_PATH="$HOME/.openfortivpn-deps/lib/pkgconfig"
          ./configure --prefix=/usr --sysconfdir=/etc
      - name: debuild
        run: debuild -b -uc -us

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-deb
          path: |
            ./*.deb
